chat_sidebar_breakpoint:
  type: string
  default: "auto"
chat_sidebar_width:
  type: string
  default: "400px"
chat_sidebar_position:
  type: enum
  default: "outside-right"
  choices:
    - left
    - right
    - outside-left
    - outside-right
chat_sidebar_theme_style:
  type: list
  list_type: simple
  choices:
    - left
    - right
    - outside-left
    - outside-right
  allow_any: false
  default: "left|right|outside-left|outside-right"
chat_sidebar_allow_user_preference:
  type: list
  list_type: simple
  choices:
    - position
  allow_any: false
  default: "position"
